pluginManagement {
    repositories {
        mavenCentral()
        maven { url = "https://plugins.gradle.org/m2/" }
        gradlePluginPortal()
    }

    plugins {
        id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin' version '3.0.1' apply false
        id 'org.openapi.generator' version '7.24.0'
        id 'io.freefair.lombok' version '9.5.0'
    }
}

rootProject.name = 'laa-claim-for-payment-stubs'

include 'stub-civil-claims-api'
include 'stub-oidc-server'
include 'authx-secondary'
// include 'spring-boot-microservice-service'
