plugins {
    id 'io.freefair.lombok'
    id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin'
    id "org.springdoc.openapi-gradle-plugin" version "1.9.0"
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    // testLogging {
    //     events "passed", "skipped", "failed", "standard_out", "standard_error"
    //     showStandardStreams = true
    // }
}

integrationTest {
    testLogging {
        events "passed", "skipped", "failed", "standard_out", "standard_error"
        showStandardStreams = true
    }
}

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/CivilClaimsStubApplication.class'])
        }))
    }
}

jacocoTestCoverageVerification {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/CivilClaimsStubApplication.class'])
        }))
    }
}

dependencies {
    checkstyle "com.puppycrawl.tools:checkstyle:${rootProject.ext.checkstyleVersion}"

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'
    implementation 'org.apache.tomcat.embed:tomcat-embed-core:11.0.24'
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.5'
    implementation 'tools.jackson.core:jackson-databind:3.1.5'

    implementation project(":authx-secondary")

    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    implementation 'org.springframework.boot:spring-boot-starter-flyway'

    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql:42.7.13'
    runtimeOnly "ch.qos.logback:logback-classic:1.6.1"
    runtimeOnly "ch.qos.logback:logback-core:1.6.1"
    implementation "org.flywaydb:flyway-core"
    implementation "org.flywaydb:flyway-database-postgresql"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"

    // Overrides to resolve vulnerabilities identified by Snyk
    implementation 'ch.qos.logback:logback-core:1.6.1'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation "org.springframework.security:spring-security-test"
    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-logging'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}
